### ISSUE TITLE
autoCheckOutToSourceControl is not supported in versions before 2023

### ISSUE THREAD

**Issue by mcsaudio** [matheusvilano/PyWwise#23]
The autoCheckOutToSourceControl argument was introduced in Wwise 2023. This means that functions that use this arg by default, such as `ak.wwise.core.object.move`, will fail when used in a project that's in 2022 or earlier.

Could functions that use these args potentially check WwiseGlobalInfo Version before adding autoCheckOutToSourceControl to args?

**Comment by matheusvilano** [comment]
Good catch! This is likely the case with anything else supporting version control args.

As for the solution: I'd like to avoid I/O operations like that, specially because WAAPI can be used remotely. Instead, I'll write a solution using `ak.wwise.core.getInfo` for validation instead. I'll have it deployed this week. 

Thanks for the report!

**Comment by matheusvilano** [comment]
@mcsaudio - I thought of an even easier fix, so [I just went ahead and fixed it now](https://github.com/matheusvilano/PyWwise/commit/c45a4362805dbcb1194a17dbe365110eaf7f248c). I'm closing this issue and I'll kickstart a hotfix build within the next hour. If you downloaded via `pip`, you'll be able to update the package normally once the build is done.
